name = "clean_lean"
version = "0.1.0"
keywords = ["mathematics", "collatz", "formalization"]
defaultTargets = ["CleanLean"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0-rc1"

[[lean_lib]]
name = "CleanLean"

