#define _POSIX_C_SOURCE 200809L
#include <gmp.h>
#include <omp.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct { unsigned long long two,three,lifts; uint64_t first_two,first_three; } result_t;
static void fail(const char*s){fprintf(stderr,"hensel_atlas: %s\n",s);exit(2);}
static unsigned L(unsigned j){uint64_t p=1;for(unsigned i=0;i<j;++i)p*=3;uint64_t z=2*p+j+4;if(z>100000)fail("counter too large");return(unsigned)z;}
static void C(mpz_t out,unsigned j){mpz_ui_pow_ui(out,3,j+1);mpz_mul_ui(out,out,7);mpz_add_ui(out,out,(unsigned long)1<<(j+4));}
static void initial(mpz_t A,mpz_t z,uint64_t c,unsigned d,const mpz_t mod,unsigned P){mpz_t t,e,period;mpz_inits(t,e,period,NULL);mpz_set_ui(t,3);mpz_ui_pow_ui(period,2,P-3);mpz_powm_ui(e,t,(unsigned long)c,period);mpz_mul_ui(e,e,2);mpz_add_ui(e,e,d+1);mpz_mul_ui(period,period,2);mpz_powm(A,t,e,mod);mpz_powm_ui(z,t,(unsigned long)(c+1),mod);mpz_clears(t,e,period,NULL);}
static void scan_chunk(uint64_t lo,uint64_t hi,unsigned d,unsigned e,unsigned f,result_t*r){unsigned ld=L(d),le=L(e),lf=L(f),P=ld+le+lf+1;mpz_t mod,A,z,invA,invz,cd,ce,cf,target,small,h,q,first,composite,tmp,powde,powef,divisor,invden,inv3;mpz_inits(mod,A,z,invA,invz,cd,ce,cf,target,small,h,q,first,composite,tmp,powde,powef,divisor,invden,inv3,NULL);mpz_ui_pow_ui(mod,2,P);initial(A,z,lo,d,mod,P);if(!mpz_invert(invA,A,mod)||!mpz_invert(invz,z,mod))fail("inverse failed");C(cd,d);C(ce,e);C(cf,f);mpz_ui_pow_ui(target,2,ld);mpz_ui_pow_ui(small,2,ld+1);mpz_ui_pow_ui(divisor,3,2*d+2);if(!mpz_invert(invden,divisor,mod))fail("recurrence inverse failed");mpz_set_ui(inv3,3);if(!mpz_invert(inv3,inv3,mod))fail("inverse three failed");uint64_t Md=2;for(unsigned i=0;i<d;++i)Md*=3;mpz_ui_pow_ui(powde,3,(unsigned long)(Md+e+1));uint64_t Me=2;for(unsigned i=0;i<e;++i)Me*=3;mpz_ui_pow_ui(powef,3,(unsigned long)(Me+f+1));
    for(uint64_t c=lo;c<=hi;++c){mpz_sub(h,target,A);mpz_sub(h,h,cd);mpz_mul(h,h,invA);mpz_mul(h,h,invz);mpz_mod(h,h,small);if(mpz_fdiv_ui(h,2))fail("canonical h odd");if(mpz_fdiv_ui(h,3)==2){mpz_add(h,h,small);++r->lifts;}mpz_mul(q,z,h);mpz_add_ui(q,q,1);mpz_mod(q,q,mod);mpz_mul(first,A,q);mpz_add(first,first,cd);mpz_mod(first,first,mod);mpz_fdiv_r_2exp(tmp,first,ld+1);if(mpz_cmp(tmp,target))fail("first exact link regression failed");mpz_mul(composite,powde,first);mpz_mul_2exp(tmp,ce,ld);mpz_add(composite,composite,tmp);mpz_mod(composite,composite,mod);mpz_fdiv_r_2exp(tmp,composite,ld+le+1);mpz_ui_pow_ui(target,2,ld+le);if(mpz_cmp(tmp,target)==0){++r->two;if(!r->first_two)r->first_two=c;mpz_fdiv_q_2exp(tmp,composite,ld+le);mpz_mul(tmp,tmp,powef);mpz_add(tmp,tmp,cf);if(mpz_scan1(tmp,0)==lf){++r->three;if(!r->first_three)r->first_three=c;}}mpz_ui_pow_ui(target,2,ld);
        mpz_pow_ui(A,A,3);mpz_mul(A,A,invden);mpz_mod(A,A,mod);mpz_pow_ui(invA,invA,3);mpz_mul(invA,invA,divisor);mpz_mod(invA,invA,mod);mpz_mul_ui(z,z,3);mpz_mod(z,z,mod);mpz_mul(invz,invz,inv3);mpz_mod(invz,invz,mod);if(c==UINT64_MAX)break;}
    mpz_clears(mod,A,z,invA,invz,cd,ce,cf,target,small,h,q,first,composite,tmp,powde,powef,divisor,invden,inv3,NULL);}
int main(int argc,char**argv){if(argc!=6)fail("usage: MAX_C D E F OUTPUT.tsv");uint64_t maxc=strtoull(argv[1],0,10);unsigned d=(unsigned)strtoul(argv[2],0,10),e=(unsigned)strtoul(argv[3],0,10),f=(unsigned)strtoul(argv[4],0,10);if(!maxc||d<1||e<1||f<1||d>6||e>6||f>6)fail("invalid bounds");int nt=omp_get_max_threads();result_t*rs=calloc((size_t)nt,sizeof(*rs));if(!rs)fail("allocation");double start=omp_get_wtime();
#pragma omp parallel
    {int t=omp_get_thread_num();uint64_t lo=1+(uint64_t)t*maxc/nt,hi=(uint64_t)(t+1)*maxc/nt;if(lo<=hi)scan_chunk(lo,hi,d,e,f,&rs[t]);}
    result_t z={0};for(int t=0;t<nt;++t){z.two+=rs[t].two;z.three+=rs[t].three;z.lifts+=rs[t].lifts;if(rs[t].first_two&&(!z.first_two||rs[t].first_two<z.first_two))z.first_two=rs[t].first_two;if(rs[t].first_three&&(!z.first_three||rs[t].first_three<z.first_three))z.first_three=rs[t].first_three;}FILE*out=fopen(argv[5],"w");if(!out)fail("cannot open output");fprintf(out,"# exact singular Hensel atlas c=1..%llu d=%u e=%u f=%u precision=%u threads=%d seconds=%.6f\n",(unsigned long long)maxc,d,e,f,L(d)+L(e)+L(f)+1,nt,omp_get_wtime()-start);fprintf(out,"RESULT\ttwo_link_hits=%llu\tfirst_two=%llu\tthree_link_hits=%llu\tfirst_three=%llu\tternary_lifts=%llu\tcounterexample=null\n",z.two,(unsigned long long)z.first_two,z.three,(unsigned long long)z.first_three,z.lifts);fclose(out);free(rs);return 0;}
