/- This file is generated by scripts/generate_finite_record_k12.py.
Source SHA-256: a6386bfc8d0410a3dd82a98d765690e53c620259e6b7c4a5359f150ce6d1459f
-/
import CleanLean.KL.FiniteRecordK12Core

namespace CleanLean.KL.FiniteRecordK12

/- Synchronous elaboration bounds peak memory.  Each module is
an independently cached group of at most 4,096 exact rows. -/
set_option Elab.async false

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid256 :
    ChunkValid
      ⟨256, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid257 :
    ChunkValid
      ⟨257, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid258 :
    ChunkValid
      ⟨258, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid259 :
    ChunkValid
      ⟨259, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid260 :
    ChunkValid
      ⟨260, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid261 :
    ChunkValid
      ⟨261, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid262 :
    ChunkValid
      ⟨262, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid263 :
    ChunkValid
      ⟨263, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid264 :
    ChunkValid
      ⟨264, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid265 :
    ChunkValid
      ⟨265, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid266 :
    ChunkValid
      ⟨266, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid267 :
    ChunkValid
      ⟨267, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid268 :
    ChunkValid
      ⟨268, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid269 :
    ChunkValid
      ⟨269, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid270 :
    ChunkValid
      ⟨270, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid271 :
    ChunkValid
      ⟨271, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid272 :
    ChunkValid
      ⟨272, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid273 :
    ChunkValid
      ⟨273, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid274 :
    ChunkValid
      ⟨274, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid275 :
    ChunkValid
      ⟨275, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid276 :
    ChunkValid
      ⟨276, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid277 :
    ChunkValid
      ⟨277, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid278 :
    ChunkValid
      ⟨278, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid279 :
    ChunkValid
      ⟨279, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid280 :
    ChunkValid
      ⟨280, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid281 :
    ChunkValid
      ⟨281, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid282 :
    ChunkValid
      ⟨282, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid283 :
    ChunkValid
      ⟨283, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid284 :
    ChunkValid
      ⟨284, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid285 :
    ChunkValid
      ⟨285, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid286 :
    ChunkValid
      ⟨286, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid287 :
    ChunkValid
      ⟨287, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid288 :
    ChunkValid
      ⟨288, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid289 :
    ChunkValid
      ⟨289, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid290 :
    ChunkValid
      ⟨290, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid291 :
    ChunkValid
      ⟨291, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid292 :
    ChunkValid
      ⟨292, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid293 :
    ChunkValid
      ⟨293, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid294 :
    ChunkValid
      ⟨294, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid295 :
    ChunkValid
      ⟨295, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid296 :
    ChunkValid
      ⟨296, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid297 :
    ChunkValid
      ⟨297, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid298 :
    ChunkValid
      ⟨298, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid299 :
    ChunkValid
      ⟨299, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid300 :
    ChunkValid
      ⟨300, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid301 :
    ChunkValid
      ⟨301, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid302 :
    ChunkValid
      ⟨302, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid303 :
    ChunkValid
      ⟨303, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid304 :
    ChunkValid
      ⟨304, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid305 :
    ChunkValid
      ⟨305, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid306 :
    ChunkValid
      ⟨306, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid307 :
    ChunkValid
      ⟨307, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid308 :
    ChunkValid
      ⟨308, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid309 :
    ChunkValid
      ⟨309, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid310 :
    ChunkValid
      ⟨310, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid311 :
    ChunkValid
      ⟨311, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid312 :
    ChunkValid
      ⟨312, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid313 :
    ChunkValid
      ⟨313, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid314 :
    ChunkValid
      ⟨314, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid315 :
    ChunkValid
      ⟨315, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid316 :
    ChunkValid
      ⟨316, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid317 :
    ChunkValid
      ⟨317, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid318 :
    ChunkValid
      ⟨318, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid319 :
    ChunkValid
      ⟨319, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- The explicit finite case split covers all 64 group offsets.
theorem groupValid4 :
    ChunkGroupValid
      ⟨4, by norm_num [groupCount]⟩ := by
  intro offset hidx
  fin_cases offset
  · simpa [chunksPerGroup] using chunkValid256
  · simpa [chunksPerGroup] using chunkValid257
  · simpa [chunksPerGroup] using chunkValid258
  · simpa [chunksPerGroup] using chunkValid259
  · simpa [chunksPerGroup] using chunkValid260
  · simpa [chunksPerGroup] using chunkValid261
  · simpa [chunksPerGroup] using chunkValid262
  · simpa [chunksPerGroup] using chunkValid263
  · simpa [chunksPerGroup] using chunkValid264
  · simpa [chunksPerGroup] using chunkValid265
  · simpa [chunksPerGroup] using chunkValid266
  · simpa [chunksPerGroup] using chunkValid267
  · simpa [chunksPerGroup] using chunkValid268
  · simpa [chunksPerGroup] using chunkValid269
  · simpa [chunksPerGroup] using chunkValid270
  · simpa [chunksPerGroup] using chunkValid271
  · simpa [chunksPerGroup] using chunkValid272
  · simpa [chunksPerGroup] using chunkValid273
  · simpa [chunksPerGroup] using chunkValid274
  · simpa [chunksPerGroup] using chunkValid275
  · simpa [chunksPerGroup] using chunkValid276
  · simpa [chunksPerGroup] using chunkValid277
  · simpa [chunksPerGroup] using chunkValid278
  · simpa [chunksPerGroup] using chunkValid279
  · simpa [chunksPerGroup] using chunkValid280
  · simpa [chunksPerGroup] using chunkValid281
  · simpa [chunksPerGroup] using chunkValid282
  · simpa [chunksPerGroup] using chunkValid283
  · simpa [chunksPerGroup] using chunkValid284
  · simpa [chunksPerGroup] using chunkValid285
  · simpa [chunksPerGroup] using chunkValid286
  · simpa [chunksPerGroup] using chunkValid287
  · simpa [chunksPerGroup] using chunkValid288
  · simpa [chunksPerGroup] using chunkValid289
  · simpa [chunksPerGroup] using chunkValid290
  · simpa [chunksPerGroup] using chunkValid291
  · simpa [chunksPerGroup] using chunkValid292
  · simpa [chunksPerGroup] using chunkValid293
  · simpa [chunksPerGroup] using chunkValid294
  · simpa [chunksPerGroup] using chunkValid295
  · simpa [chunksPerGroup] using chunkValid296
  · simpa [chunksPerGroup] using chunkValid297
  · simpa [chunksPerGroup] using chunkValid298
  · simpa [chunksPerGroup] using chunkValid299
  · simpa [chunksPerGroup] using chunkValid300
  · simpa [chunksPerGroup] using chunkValid301
  · simpa [chunksPerGroup] using chunkValid302
  · simpa [chunksPerGroup] using chunkValid303
  · simpa [chunksPerGroup] using chunkValid304
  · simpa [chunksPerGroup] using chunkValid305
  · simpa [chunksPerGroup] using chunkValid306
  · simpa [chunksPerGroup] using chunkValid307
  · simpa [chunksPerGroup] using chunkValid308
  · simpa [chunksPerGroup] using chunkValid309
  · simpa [chunksPerGroup] using chunkValid310
  · simpa [chunksPerGroup] using chunkValid311
  · simpa [chunksPerGroup] using chunkValid312
  · simpa [chunksPerGroup] using chunkValid313
  · simpa [chunksPerGroup] using chunkValid314
  · simpa [chunksPerGroup] using chunkValid315
  · simpa [chunksPerGroup] using chunkValid316
  · simpa [chunksPerGroup] using chunkValid317
  · simpa [chunksPerGroup] using chunkValid318
  · simpa [chunksPerGroup] using chunkValid319

end CleanLean.KL.FiniteRecordK12
