/- This file is generated by scripts/generate_finite_record_k12.py.
Source SHA-256: a6386bfc8d0410a3dd82a98d765690e53c620259e6b7c4a5359f150ce6d1459f
-/
import CleanLean.KL.FiniteRecordK12Core

namespace CleanLean.KL.FiniteRecordK12

/- Synchronous elaboration bounds peak memory.  Each module is
an independently cached group of at most 4,096 exact rows. -/
set_option Elab.async false

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1344 :
    ChunkValid
      ⟨1344, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1345 :
    ChunkValid
      ⟨1345, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1346 :
    ChunkValid
      ⟨1346, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1347 :
    ChunkValid
      ⟨1347, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1348 :
    ChunkValid
      ⟨1348, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1349 :
    ChunkValid
      ⟨1349, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1350 :
    ChunkValid
      ⟨1350, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1351 :
    ChunkValid
      ⟨1351, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1352 :
    ChunkValid
      ⟨1352, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1353 :
    ChunkValid
      ⟨1353, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1354 :
    ChunkValid
      ⟨1354, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1355 :
    ChunkValid
      ⟨1355, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1356 :
    ChunkValid
      ⟨1356, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1357 :
    ChunkValid
      ⟨1357, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1358 :
    ChunkValid
      ⟨1358, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1359 :
    ChunkValid
      ⟨1359, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1360 :
    ChunkValid
      ⟨1360, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1361 :
    ChunkValid
      ⟨1361, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1362 :
    ChunkValid
      ⟨1362, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1363 :
    ChunkValid
      ⟨1363, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1364 :
    ChunkValid
      ⟨1364, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1365 :
    ChunkValid
      ⟨1365, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1366 :
    ChunkValid
      ⟨1366, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1367 :
    ChunkValid
      ⟨1367, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1368 :
    ChunkValid
      ⟨1368, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1369 :
    ChunkValid
      ⟨1369, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1370 :
    ChunkValid
      ⟨1370, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1371 :
    ChunkValid
      ⟨1371, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1372 :
    ChunkValid
      ⟨1372, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1373 :
    ChunkValid
      ⟨1373, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1374 :
    ChunkValid
      ⟨1374, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1375 :
    ChunkValid
      ⟨1375, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1376 :
    ChunkValid
      ⟨1376, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1377 :
    ChunkValid
      ⟨1377, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1378 :
    ChunkValid
      ⟨1378, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1379 :
    ChunkValid
      ⟨1379, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1380 :
    ChunkValid
      ⟨1380, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1381 :
    ChunkValid
      ⟨1381, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1382 :
    ChunkValid
      ⟨1382, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1383 :
    ChunkValid
      ⟨1383, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1384 :
    ChunkValid
      ⟨1384, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1385 :
    ChunkValid
      ⟨1385, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1386 :
    ChunkValid
      ⟨1386, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1387 :
    ChunkValid
      ⟨1387, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1388 :
    ChunkValid
      ⟨1388, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1389 :
    ChunkValid
      ⟨1389, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1390 :
    ChunkValid
      ⟨1390, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1391 :
    ChunkValid
      ⟨1391, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1392 :
    ChunkValid
      ⟨1392, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1393 :
    ChunkValid
      ⟨1393, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1394 :
    ChunkValid
      ⟨1394, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1395 :
    ChunkValid
      ⟨1395, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1396 :
    ChunkValid
      ⟨1396, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1397 :
    ChunkValid
      ⟨1397, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1398 :
    ChunkValid
      ⟨1398, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1399 :
    ChunkValid
      ⟨1399, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1400 :
    ChunkValid
      ⟨1400, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1401 :
    ChunkValid
      ⟨1401, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1402 :
    ChunkValid
      ⟨1402, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1403 :
    ChunkValid
      ⟨1403, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1404 :
    ChunkValid
      ⟨1404, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1405 :
    ChunkValid
      ⟨1405, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1406 :
    ChunkValid
      ⟨1406, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1407 :
    ChunkValid
      ⟨1407, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- The explicit finite case split covers all 64 group offsets.
theorem groupValid21 :
    ChunkGroupValid
      ⟨21, by norm_num [groupCount]⟩ := by
  intro offset hidx
  fin_cases offset
  · simpa [chunksPerGroup] using chunkValid1344
  · simpa [chunksPerGroup] using chunkValid1345
  · simpa [chunksPerGroup] using chunkValid1346
  · simpa [chunksPerGroup] using chunkValid1347
  · simpa [chunksPerGroup] using chunkValid1348
  · simpa [chunksPerGroup] using chunkValid1349
  · simpa [chunksPerGroup] using chunkValid1350
  · simpa [chunksPerGroup] using chunkValid1351
  · simpa [chunksPerGroup] using chunkValid1352
  · simpa [chunksPerGroup] using chunkValid1353
  · simpa [chunksPerGroup] using chunkValid1354
  · simpa [chunksPerGroup] using chunkValid1355
  · simpa [chunksPerGroup] using chunkValid1356
  · simpa [chunksPerGroup] using chunkValid1357
  · simpa [chunksPerGroup] using chunkValid1358
  · simpa [chunksPerGroup] using chunkValid1359
  · simpa [chunksPerGroup] using chunkValid1360
  · simpa [chunksPerGroup] using chunkValid1361
  · simpa [chunksPerGroup] using chunkValid1362
  · simpa [chunksPerGroup] using chunkValid1363
  · simpa [chunksPerGroup] using chunkValid1364
  · simpa [chunksPerGroup] using chunkValid1365
  · simpa [chunksPerGroup] using chunkValid1366
  · simpa [chunksPerGroup] using chunkValid1367
  · simpa [chunksPerGroup] using chunkValid1368
  · simpa [chunksPerGroup] using chunkValid1369
  · simpa [chunksPerGroup] using chunkValid1370
  · simpa [chunksPerGroup] using chunkValid1371
  · simpa [chunksPerGroup] using chunkValid1372
  · simpa [chunksPerGroup] using chunkValid1373
  · simpa [chunksPerGroup] using chunkValid1374
  · simpa [chunksPerGroup] using chunkValid1375
  · simpa [chunksPerGroup] using chunkValid1376
  · simpa [chunksPerGroup] using chunkValid1377
  · simpa [chunksPerGroup] using chunkValid1378
  · simpa [chunksPerGroup] using chunkValid1379
  · simpa [chunksPerGroup] using chunkValid1380
  · simpa [chunksPerGroup] using chunkValid1381
  · simpa [chunksPerGroup] using chunkValid1382
  · simpa [chunksPerGroup] using chunkValid1383
  · simpa [chunksPerGroup] using chunkValid1384
  · simpa [chunksPerGroup] using chunkValid1385
  · simpa [chunksPerGroup] using chunkValid1386
  · simpa [chunksPerGroup] using chunkValid1387
  · simpa [chunksPerGroup] using chunkValid1388
  · simpa [chunksPerGroup] using chunkValid1389
  · simpa [chunksPerGroup] using chunkValid1390
  · simpa [chunksPerGroup] using chunkValid1391
  · simpa [chunksPerGroup] using chunkValid1392
  · simpa [chunksPerGroup] using chunkValid1393
  · simpa [chunksPerGroup] using chunkValid1394
  · simpa [chunksPerGroup] using chunkValid1395
  · simpa [chunksPerGroup] using chunkValid1396
  · simpa [chunksPerGroup] using chunkValid1397
  · simpa [chunksPerGroup] using chunkValid1398
  · simpa [chunksPerGroup] using chunkValid1399
  · simpa [chunksPerGroup] using chunkValid1400
  · simpa [chunksPerGroup] using chunkValid1401
  · simpa [chunksPerGroup] using chunkValid1402
  · simpa [chunksPerGroup] using chunkValid1403
  · simpa [chunksPerGroup] using chunkValid1404
  · simpa [chunksPerGroup] using chunkValid1405
  · simpa [chunksPerGroup] using chunkValid1406
  · simpa [chunksPerGroup] using chunkValid1407

end CleanLean.KL.FiniteRecordK12
