/- This file is generated by scripts/generate_finite_record_k12.py.
Source SHA-256: a6386bfc8d0410a3dd82a98d765690e53c620259e6b7c4a5359f150ce6d1459f
-/
import CleanLean.KL.FiniteRecordK12Core

namespace CleanLean.KL.FiniteRecordK12

/- Synchronous elaboration bounds peak memory.  Each module is
an independently cached group of at most 4,096 exact rows. -/
set_option Elab.async false

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1408 :
    ChunkValid
      ⟨1408, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1409 :
    ChunkValid
      ⟨1409, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1410 :
    ChunkValid
      ⟨1410, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1411 :
    ChunkValid
      ⟨1411, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1412 :
    ChunkValid
      ⟨1412, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1413 :
    ChunkValid
      ⟨1413, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1414 :
    ChunkValid
      ⟨1414, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1415 :
    ChunkValid
      ⟨1415, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1416 :
    ChunkValid
      ⟨1416, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1417 :
    ChunkValid
      ⟨1417, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1418 :
    ChunkValid
      ⟨1418, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1419 :
    ChunkValid
      ⟨1419, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1420 :
    ChunkValid
      ⟨1420, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1421 :
    ChunkValid
      ⟨1421, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1422 :
    ChunkValid
      ⟨1422, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1423 :
    ChunkValid
      ⟨1423, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1424 :
    ChunkValid
      ⟨1424, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1425 :
    ChunkValid
      ⟨1425, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1426 :
    ChunkValid
      ⟨1426, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1427 :
    ChunkValid
      ⟨1427, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1428 :
    ChunkValid
      ⟨1428, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1429 :
    ChunkValid
      ⟨1429, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1430 :
    ChunkValid
      ⟨1430, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1431 :
    ChunkValid
      ⟨1431, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1432 :
    ChunkValid
      ⟨1432, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1433 :
    ChunkValid
      ⟨1433, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1434 :
    ChunkValid
      ⟨1434, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1435 :
    ChunkValid
      ⟨1435, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1436 :
    ChunkValid
      ⟨1436, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1437 :
    ChunkValid
      ⟨1437, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1438 :
    ChunkValid
      ⟨1438, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1439 :
    ChunkValid
      ⟨1439, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1440 :
    ChunkValid
      ⟨1440, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1441 :
    ChunkValid
      ⟨1441, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1442 :
    ChunkValid
      ⟨1442, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1443 :
    ChunkValid
      ⟨1443, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1444 :
    ChunkValid
      ⟨1444, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1445 :
    ChunkValid
      ⟨1445, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1446 :
    ChunkValid
      ⟨1446, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1447 :
    ChunkValid
      ⟨1447, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1448 :
    ChunkValid
      ⟨1448, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1449 :
    ChunkValid
      ⟨1449, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1450 :
    ChunkValid
      ⟨1450, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1451 :
    ChunkValid
      ⟨1451, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1452 :
    ChunkValid
      ⟨1452, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1453 :
    ChunkValid
      ⟨1453, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1454 :
    ChunkValid
      ⟨1454, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1455 :
    ChunkValid
      ⟨1455, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1456 :
    ChunkValid
      ⟨1456, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1457 :
    ChunkValid
      ⟨1457, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1458 :
    ChunkValid
      ⟨1458, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1459 :
    ChunkValid
      ⟨1459, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1460 :
    ChunkValid
      ⟨1460, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1461 :
    ChunkValid
      ⟨1461, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1462 :
    ChunkValid
      ⟨1462, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1463 :
    ChunkValid
      ⟨1463, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1464 :
    ChunkValid
      ⟨1464, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1465 :
    ChunkValid
      ⟨1465, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1466 :
    ChunkValid
      ⟨1466, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1467 :
    ChunkValid
      ⟨1467, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1468 :
    ChunkValid
      ⟨1468, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1469 :
    ChunkValid
      ⟨1469, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1470 :
    ChunkValid
      ⟨1470, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid1471 :
    ChunkValid
      ⟨1471, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- The explicit finite case split covers all 64 group offsets.
theorem groupValid22 :
    ChunkGroupValid
      ⟨22, by norm_num [groupCount]⟩ := by
  intro offset hidx
  fin_cases offset
  · simpa [chunksPerGroup] using chunkValid1408
  · simpa [chunksPerGroup] using chunkValid1409
  · simpa [chunksPerGroup] using chunkValid1410
  · simpa [chunksPerGroup] using chunkValid1411
  · simpa [chunksPerGroup] using chunkValid1412
  · simpa [chunksPerGroup] using chunkValid1413
  · simpa [chunksPerGroup] using chunkValid1414
  · simpa [chunksPerGroup] using chunkValid1415
  · simpa [chunksPerGroup] using chunkValid1416
  · simpa [chunksPerGroup] using chunkValid1417
  · simpa [chunksPerGroup] using chunkValid1418
  · simpa [chunksPerGroup] using chunkValid1419
  · simpa [chunksPerGroup] using chunkValid1420
  · simpa [chunksPerGroup] using chunkValid1421
  · simpa [chunksPerGroup] using chunkValid1422
  · simpa [chunksPerGroup] using chunkValid1423
  · simpa [chunksPerGroup] using chunkValid1424
  · simpa [chunksPerGroup] using chunkValid1425
  · simpa [chunksPerGroup] using chunkValid1426
  · simpa [chunksPerGroup] using chunkValid1427
  · simpa [chunksPerGroup] using chunkValid1428
  · simpa [chunksPerGroup] using chunkValid1429
  · simpa [chunksPerGroup] using chunkValid1430
  · simpa [chunksPerGroup] using chunkValid1431
  · simpa [chunksPerGroup] using chunkValid1432
  · simpa [chunksPerGroup] using chunkValid1433
  · simpa [chunksPerGroup] using chunkValid1434
  · simpa [chunksPerGroup] using chunkValid1435
  · simpa [chunksPerGroup] using chunkValid1436
  · simpa [chunksPerGroup] using chunkValid1437
  · simpa [chunksPerGroup] using chunkValid1438
  · simpa [chunksPerGroup] using chunkValid1439
  · simpa [chunksPerGroup] using chunkValid1440
  · simpa [chunksPerGroup] using chunkValid1441
  · simpa [chunksPerGroup] using chunkValid1442
  · simpa [chunksPerGroup] using chunkValid1443
  · simpa [chunksPerGroup] using chunkValid1444
  · simpa [chunksPerGroup] using chunkValid1445
  · simpa [chunksPerGroup] using chunkValid1446
  · simpa [chunksPerGroup] using chunkValid1447
  · simpa [chunksPerGroup] using chunkValid1448
  · simpa [chunksPerGroup] using chunkValid1449
  · simpa [chunksPerGroup] using chunkValid1450
  · simpa [chunksPerGroup] using chunkValid1451
  · simpa [chunksPerGroup] using chunkValid1452
  · simpa [chunksPerGroup] using chunkValid1453
  · simpa [chunksPerGroup] using chunkValid1454
  · simpa [chunksPerGroup] using chunkValid1455
  · simpa [chunksPerGroup] using chunkValid1456
  · simpa [chunksPerGroup] using chunkValid1457
  · simpa [chunksPerGroup] using chunkValid1458
  · simpa [chunksPerGroup] using chunkValid1459
  · simpa [chunksPerGroup] using chunkValid1460
  · simpa [chunksPerGroup] using chunkValid1461
  · simpa [chunksPerGroup] using chunkValid1462
  · simpa [chunksPerGroup] using chunkValid1463
  · simpa [chunksPerGroup] using chunkValid1464
  · simpa [chunksPerGroup] using chunkValid1465
  · simpa [chunksPerGroup] using chunkValid1466
  · simpa [chunksPerGroup] using chunkValid1467
  · simpa [chunksPerGroup] using chunkValid1468
  · simpa [chunksPerGroup] using chunkValid1469
  · simpa [chunksPerGroup] using chunkValid1470
  · simpa [chunksPerGroup] using chunkValid1471

end CleanLean.KL.FiniteRecordK12
