/- This file is generated by scripts/generate_finite_record_k12.py.
Source SHA-256: a6386bfc8d0410a3dd82a98d765690e53c620259e6b7c4a5359f150ce6d1459f
-/
import CleanLean.KL.FiniteRecordK12Core

namespace CleanLean.KL.FiniteRecordK12

/- Synchronous elaboration bounds peak memory.  Each module is
an independently cached group of at most 4,096 exact rows. -/
set_option Elab.async false

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid64 :
    ChunkValid
      ⟨64, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid65 :
    ChunkValid
      ⟨65, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid66 :
    ChunkValid
      ⟨66, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid67 :
    ChunkValid
      ⟨67, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid68 :
    ChunkValid
      ⟨68, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid69 :
    ChunkValid
      ⟨69, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid70 :
    ChunkValid
      ⟨70, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid71 :
    ChunkValid
      ⟨71, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid72 :
    ChunkValid
      ⟨72, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid73 :
    ChunkValid
      ⟨73, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid74 :
    ChunkValid
      ⟨74, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid75 :
    ChunkValid
      ⟨75, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid76 :
    ChunkValid
      ⟨76, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid77 :
    ChunkValid
      ⟨77, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid78 :
    ChunkValid
      ⟨78, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid79 :
    ChunkValid
      ⟨79, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid80 :
    ChunkValid
      ⟨80, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid81 :
    ChunkValid
      ⟨81, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid82 :
    ChunkValid
      ⟨82, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid83 :
    ChunkValid
      ⟨83, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid84 :
    ChunkValid
      ⟨84, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid85 :
    ChunkValid
      ⟨85, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid86 :
    ChunkValid
      ⟨86, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid87 :
    ChunkValid
      ⟨87, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid88 :
    ChunkValid
      ⟨88, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid89 :
    ChunkValid
      ⟨89, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid90 :
    ChunkValid
      ⟨90, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid91 :
    ChunkValid
      ⟨91, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid92 :
    ChunkValid
      ⟨92, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid93 :
    ChunkValid
      ⟨93, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid94 :
    ChunkValid
      ⟨94, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid95 :
    ChunkValid
      ⟨95, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid96 :
    ChunkValid
      ⟨96, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid97 :
    ChunkValid
      ⟨97, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid98 :
    ChunkValid
      ⟨98, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid99 :
    ChunkValid
      ⟨99, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid100 :
    ChunkValid
      ⟨100, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid101 :
    ChunkValid
      ⟨101, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid102 :
    ChunkValid
      ⟨102, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid103 :
    ChunkValid
      ⟨103, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid104 :
    ChunkValid
      ⟨104, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid105 :
    ChunkValid
      ⟨105, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid106 :
    ChunkValid
      ⟨106, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid107 :
    ChunkValid
      ⟨107, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid108 :
    ChunkValid
      ⟨108, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid109 :
    ChunkValid
      ⟨109, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid110 :
    ChunkValid
      ⟨110, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid111 :
    ChunkValid
      ⟨111, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid112 :
    ChunkValid
      ⟨112, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid113 :
    ChunkValid
      ⟨113, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid114 :
    ChunkValid
      ⟨114, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid115 :
    ChunkValid
      ⟨115, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid116 :
    ChunkValid
      ⟨116, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid117 :
    ChunkValid
      ⟨117, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid118 :
    ChunkValid
      ⟨118, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid119 :
    ChunkValid
      ⟨119, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid120 :
    ChunkValid
      ⟨120, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid121 :
    ChunkValid
      ⟨121, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid122 :
    ChunkValid
      ⟨122, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid123 :
    ChunkValid
      ⟨123, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid124 :
    ChunkValid
      ⟨124, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid125 :
    ChunkValid
      ⟨125, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid126 :
    ChunkValid
      ⟨126, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid127 :
    ChunkValid
      ⟨127, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- The explicit finite case split covers all 64 group offsets.
theorem groupValid1 :
    ChunkGroupValid
      ⟨1, by norm_num [groupCount]⟩ := by
  intro offset hidx
  fin_cases offset
  · simpa [chunksPerGroup] using chunkValid64
  · simpa [chunksPerGroup] using chunkValid65
  · simpa [chunksPerGroup] using chunkValid66
  · simpa [chunksPerGroup] using chunkValid67
  · simpa [chunksPerGroup] using chunkValid68
  · simpa [chunksPerGroup] using chunkValid69
  · simpa [chunksPerGroup] using chunkValid70
  · simpa [chunksPerGroup] using chunkValid71
  · simpa [chunksPerGroup] using chunkValid72
  · simpa [chunksPerGroup] using chunkValid73
  · simpa [chunksPerGroup] using chunkValid74
  · simpa [chunksPerGroup] using chunkValid75
  · simpa [chunksPerGroup] using chunkValid76
  · simpa [chunksPerGroup] using chunkValid77
  · simpa [chunksPerGroup] using chunkValid78
  · simpa [chunksPerGroup] using chunkValid79
  · simpa [chunksPerGroup] using chunkValid80
  · simpa [chunksPerGroup] using chunkValid81
  · simpa [chunksPerGroup] using chunkValid82
  · simpa [chunksPerGroup] using chunkValid83
  · simpa [chunksPerGroup] using chunkValid84
  · simpa [chunksPerGroup] using chunkValid85
  · simpa [chunksPerGroup] using chunkValid86
  · simpa [chunksPerGroup] using chunkValid87
  · simpa [chunksPerGroup] using chunkValid88
  · simpa [chunksPerGroup] using chunkValid89
  · simpa [chunksPerGroup] using chunkValid90
  · simpa [chunksPerGroup] using chunkValid91
  · simpa [chunksPerGroup] using chunkValid92
  · simpa [chunksPerGroup] using chunkValid93
  · simpa [chunksPerGroup] using chunkValid94
  · simpa [chunksPerGroup] using chunkValid95
  · simpa [chunksPerGroup] using chunkValid96
  · simpa [chunksPerGroup] using chunkValid97
  · simpa [chunksPerGroup] using chunkValid98
  · simpa [chunksPerGroup] using chunkValid99
  · simpa [chunksPerGroup] using chunkValid100
  · simpa [chunksPerGroup] using chunkValid101
  · simpa [chunksPerGroup] using chunkValid102
  · simpa [chunksPerGroup] using chunkValid103
  · simpa [chunksPerGroup] using chunkValid104
  · simpa [chunksPerGroup] using chunkValid105
  · simpa [chunksPerGroup] using chunkValid106
  · simpa [chunksPerGroup] using chunkValid107
  · simpa [chunksPerGroup] using chunkValid108
  · simpa [chunksPerGroup] using chunkValid109
  · simpa [chunksPerGroup] using chunkValid110
  · simpa [chunksPerGroup] using chunkValid111
  · simpa [chunksPerGroup] using chunkValid112
  · simpa [chunksPerGroup] using chunkValid113
  · simpa [chunksPerGroup] using chunkValid114
  · simpa [chunksPerGroup] using chunkValid115
  · simpa [chunksPerGroup] using chunkValid116
  · simpa [chunksPerGroup] using chunkValid117
  · simpa [chunksPerGroup] using chunkValid118
  · simpa [chunksPerGroup] using chunkValid119
  · simpa [chunksPerGroup] using chunkValid120
  · simpa [chunksPerGroup] using chunkValid121
  · simpa [chunksPerGroup] using chunkValid122
  · simpa [chunksPerGroup] using chunkValid123
  · simpa [chunksPerGroup] using chunkValid124
  · simpa [chunksPerGroup] using chunkValid125
  · simpa [chunksPerGroup] using chunkValid126
  · simpa [chunksPerGroup] using chunkValid127

end CleanLean.KL.FiniteRecordK12
