/- This file is generated by scripts/generate_finite_record_k12.py.
Source SHA-256: a6386bfc8d0410a3dd82a98d765690e53c620259e6b7c4a5359f150ce6d1459f
-/
import CleanLean.KL.FiniteRecordK12Core

namespace CleanLean.KL.FiniteRecordK12

/- Synchronous elaboration bounds peak memory.  Each module is
an independently cached group of at most 4,096 exact rows. -/
set_option Elab.async false

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid832 :
    ChunkValid
      ⟨832, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid833 :
    ChunkValid
      ⟨833, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid834 :
    ChunkValid
      ⟨834, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid835 :
    ChunkValid
      ⟨835, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid836 :
    ChunkValid
      ⟨836, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid837 :
    ChunkValid
      ⟨837, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid838 :
    ChunkValid
      ⟨838, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid839 :
    ChunkValid
      ⟨839, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid840 :
    ChunkValid
      ⟨840, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid841 :
    ChunkValid
      ⟨841, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid842 :
    ChunkValid
      ⟨842, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid843 :
    ChunkValid
      ⟨843, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid844 :
    ChunkValid
      ⟨844, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid845 :
    ChunkValid
      ⟨845, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid846 :
    ChunkValid
      ⟨846, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid847 :
    ChunkValid
      ⟨847, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid848 :
    ChunkValid
      ⟨848, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid849 :
    ChunkValid
      ⟨849, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid850 :
    ChunkValid
      ⟨850, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid851 :
    ChunkValid
      ⟨851, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid852 :
    ChunkValid
      ⟨852, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid853 :
    ChunkValid
      ⟨853, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid854 :
    ChunkValid
      ⟨854, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid855 :
    ChunkValid
      ⟨855, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid856 :
    ChunkValid
      ⟨856, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid857 :
    ChunkValid
      ⟨857, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid858 :
    ChunkValid
      ⟨858, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid859 :
    ChunkValid
      ⟨859, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid860 :
    ChunkValid
      ⟨860, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid861 :
    ChunkValid
      ⟨861, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid862 :
    ChunkValid
      ⟨862, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid863 :
    ChunkValid
      ⟨863, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid864 :
    ChunkValid
      ⟨864, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid865 :
    ChunkValid
      ⟨865, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid866 :
    ChunkValid
      ⟨866, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid867 :
    ChunkValid
      ⟨867, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid868 :
    ChunkValid
      ⟨868, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid869 :
    ChunkValid
      ⟨869, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid870 :
    ChunkValid
      ⟨870, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid871 :
    ChunkValid
      ⟨871, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid872 :
    ChunkValid
      ⟨872, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid873 :
    ChunkValid
      ⟨873, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid874 :
    ChunkValid
      ⟨874, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid875 :
    ChunkValid
      ⟨875, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid876 :
    ChunkValid
      ⟨876, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid877 :
    ChunkValid
      ⟨877, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid878 :
    ChunkValid
      ⟨878, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid879 :
    ChunkValid
      ⟨879, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid880 :
    ChunkValid
      ⟨880, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid881 :
    ChunkValid
      ⟨881, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid882 :
    ChunkValid
      ⟨882, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid883 :
    ChunkValid
      ⟨883, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid884 :
    ChunkValid
      ⟨884, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid885 :
    ChunkValid
      ⟨885, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid886 :
    ChunkValid
      ⟨886, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid887 :
    ChunkValid
      ⟨887, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid888 :
    ChunkValid
      ⟨888, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid889 :
    ChunkValid
      ⟨889, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid890 :
    ChunkValid
      ⟨890, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid891 :
    ChunkValid
      ⟨891, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid892 :
    ChunkValid
      ⟨892, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid893 :
    ChunkValid
      ⟨893, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid894 :
    ChunkValid
      ⟨894, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- Exact reduction of one bounded certificate block.
set_option maxRecDepth 1000000 in
theorem chunkValid895 :
    ChunkValid
      ⟨895, by norm_num [chunkCount]⟩ := by
  apply (checkChunk_eq_true_iff _).1
  rfl

set_option maxHeartbeats 0 in
-- The explicit finite case split covers all 64 group offsets.
theorem groupValid13 :
    ChunkGroupValid
      ⟨13, by norm_num [groupCount]⟩ := by
  intro offset hidx
  fin_cases offset
  · simpa [chunksPerGroup] using chunkValid832
  · simpa [chunksPerGroup] using chunkValid833
  · simpa [chunksPerGroup] using chunkValid834
  · simpa [chunksPerGroup] using chunkValid835
  · simpa [chunksPerGroup] using chunkValid836
  · simpa [chunksPerGroup] using chunkValid837
  · simpa [chunksPerGroup] using chunkValid838
  · simpa [chunksPerGroup] using chunkValid839
  · simpa [chunksPerGroup] using chunkValid840
  · simpa [chunksPerGroup] using chunkValid841
  · simpa [chunksPerGroup] using chunkValid842
  · simpa [chunksPerGroup] using chunkValid843
  · simpa [chunksPerGroup] using chunkValid844
  · simpa [chunksPerGroup] using chunkValid845
  · simpa [chunksPerGroup] using chunkValid846
  · simpa [chunksPerGroup] using chunkValid847
  · simpa [chunksPerGroup] using chunkValid848
  · simpa [chunksPerGroup] using chunkValid849
  · simpa [chunksPerGroup] using chunkValid850
  · simpa [chunksPerGroup] using chunkValid851
  · simpa [chunksPerGroup] using chunkValid852
  · simpa [chunksPerGroup] using chunkValid853
  · simpa [chunksPerGroup] using chunkValid854
  · simpa [chunksPerGroup] using chunkValid855
  · simpa [chunksPerGroup] using chunkValid856
  · simpa [chunksPerGroup] using chunkValid857
  · simpa [chunksPerGroup] using chunkValid858
  · simpa [chunksPerGroup] using chunkValid859
  · simpa [chunksPerGroup] using chunkValid860
  · simpa [chunksPerGroup] using chunkValid861
  · simpa [chunksPerGroup] using chunkValid862
  · simpa [chunksPerGroup] using chunkValid863
  · simpa [chunksPerGroup] using chunkValid864
  · simpa [chunksPerGroup] using chunkValid865
  · simpa [chunksPerGroup] using chunkValid866
  · simpa [chunksPerGroup] using chunkValid867
  · simpa [chunksPerGroup] using chunkValid868
  · simpa [chunksPerGroup] using chunkValid869
  · simpa [chunksPerGroup] using chunkValid870
  · simpa [chunksPerGroup] using chunkValid871
  · simpa [chunksPerGroup] using chunkValid872
  · simpa [chunksPerGroup] using chunkValid873
  · simpa [chunksPerGroup] using chunkValid874
  · simpa [chunksPerGroup] using chunkValid875
  · simpa [chunksPerGroup] using chunkValid876
  · simpa [chunksPerGroup] using chunkValid877
  · simpa [chunksPerGroup] using chunkValid878
  · simpa [chunksPerGroup] using chunkValid879
  · simpa [chunksPerGroup] using chunkValid880
  · simpa [chunksPerGroup] using chunkValid881
  · simpa [chunksPerGroup] using chunkValid882
  · simpa [chunksPerGroup] using chunkValid883
  · simpa [chunksPerGroup] using chunkValid884
  · simpa [chunksPerGroup] using chunkValid885
  · simpa [chunksPerGroup] using chunkValid886
  · simpa [chunksPerGroup] using chunkValid887
  · simpa [chunksPerGroup] using chunkValid888
  · simpa [chunksPerGroup] using chunkValid889
  · simpa [chunksPerGroup] using chunkValid890
  · simpa [chunksPerGroup] using chunkValid891
  · simpa [chunksPerGroup] using chunkValid892
  · simpa [chunksPerGroup] using chunkValid893
  · simpa [chunksPerGroup] using chunkValid894
  · simpa [chunksPerGroup] using chunkValid895

end CleanLean.KL.FiniteRecordK12
