#!/usr/bin/env python3
"""Generate the Lean data module for the exact level-12 KL certificate.

The source JSON remains the human-portable artifact.  This generator performs
no verification: it merely translates its integer fields into balanced Lean
lookup definitions.  All load-bearing inequalities are subsequently reduced
by Lean's kernel, not by this script or by the native compiler.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / "experiments" / "kl" / "cert_k12.json"
OUTPUT = ROOT / "CleanLean" / "KL" / "FiniteRecordK12Data.lean"
PROOFS = ROOT / "CleanLean" / "KL" / "FiniteRecordK12Chunks.lean"
PROOF_DIR = ROOT / "CleanLean" / "KL" / "FiniteRecordK12ChunkGroups"
DATA_CHUNK_SIZE = 64
PROOF_CHUNK_SIZE = 64


def emit_balanced_lookup(
    lines: list[str], lo: int, hi: int, indent: str
) -> None:
    """Emit a logarithmic-depth dispatch tree over data blocks."""
    if hi - lo == 1:
        lines.append(
            f"{indent}values{lo} (i % {DATA_CHUNK_SIZE})"
        )
        return
    mid = (lo + hi) // 2
    lines.append(f"{indent}if q < {mid} then")
    emit_balanced_lookup(lines, lo, mid, indent + "  ")
    lines.append(f"{indent}else")
    emit_balanced_lookup(lines, mid, hi, indent + "  ")


def emit_balanced_values(
    lines: list[str], values: list[int], lo: int, hi: int, indent: str
) -> None:
    """Emit a logarithmic-depth lookup tree inside one small data block."""
    if hi - lo == 1:
        lines.append(f"{indent}{values[lo]}")
        return
    mid = (lo + hi) // 2
    lines.append(f"{indent}if j < {mid} then")
    emit_balanced_values(lines, values, lo, mid, indent + "  ")
    lines.append(f"{indent}else")
    emit_balanced_values(lines, values, mid, hi, indent + "  ")


def main() -> None:
    payload = SOURCE.read_bytes()
    source_hash = hashlib.sha256(payload).hexdigest()
    data = json.loads(payload)
    if data["k"] != 12:
        raise ValueError(f"expected level 12, got {data['k']}")
    expected_metadata = {
        "A": 18064231,
        "SC_L": 10000000,
        "B2": 782366571504816,
        "B8": 1413285047434102,
        "SC_W": 1000000000000000,
        "P": 50508,
        "Q": 31867,
        "SC_C": 1000000000000,
    }
    actual_metadata = {key: data[key] for key in expected_metadata}
    if actual_metadata != expected_metadata:
        raise ValueError(
            f"certificate metadata mismatch: {actual_metadata!r}"
        )
    values = data["C"]
    expected = 3 ** 11
    if len(values) != expected:
        raise ValueError(f"expected {expected} coordinates, got {len(values)}")

    lines = [
        "/- This file is generated by scripts/generate_finite_record_k12.py.",
        f"Source SHA-256: {source_hash}",
        "-/",
        "namespace CleanLean.KL.FiniteRecordK12",
        "",
        f'def sourceSHA256 : String := "{source_hash}"',
        "",
    ]
    data_chunks = [
        values[start : start + DATA_CHUNK_SIZE]
        for start in range(0, len(values), DATA_CHUNK_SIZE)
    ]
    for number, chunk in enumerate(data_chunks):
        lines.extend(
            [
                "set_option maxHeartbeats 0 in",
                "set_option maxRecDepth 1000000 in",
                f"/-- Exact scaled coordinates in block {number}. -/",
                f"def values{number} (j : Nat) : Nat :=",
                f"  if j < {len(chunk)} then",
            ]
        )
        emit_balanced_values(lines, chunk, 0, len(chunk), "    ")
        lines.extend(["  else 0", ""])

    lines.extend(
        [
            "set_option maxHeartbeats 0 in",
            "set_option maxRecDepth 1000000 in",
            "/-- Total lookup assembled from the generated coordinate blocks. -/",
            "def valueAt (i : Nat) : Nat :=",
            f"  if i < {len(values)} then",
            f"    let q := i / {DATA_CHUNK_SIZE}",
        ]
    )
    emit_balanced_lookup(lines, 0, len(data_chunks), "    ")
    lines.extend(["  else 0", "", "end CleanLean.KL.FiniteRecordK12", ""])
    OUTPUT.write_text("\n".join(lines))

    proof_chunk_count = (
        len(values) + PROOF_CHUNK_SIZE - 1
    ) // PROOF_CHUNK_SIZE
    if proof_chunk_count != 2768:
        raise ValueError(f"unexpected proof block count: {proof_chunk_count}")
    chunks_per_group = 64
    group_count = (
        proof_chunk_count + chunks_per_group - 1
    ) // chunks_per_group
    if group_count != 44:
        raise ValueError(f"unexpected group count: {group_count}")
    PROOF_DIR.mkdir(exist_ok=True)
    for group in range(group_count):
        group_lines = [
            "/- This file is generated by scripts/generate_finite_record_k12.py.",
            f"Source SHA-256: {source_hash}",
            "-/",
            "import CleanLean.KL.FiniteRecordK12Core",
            "",
            "namespace CleanLean.KL.FiniteRecordK12",
            "",
            "/- Synchronous elaboration bounds peak memory.  Each module is",
            "an independently cached group of at most 4,096 exact rows. -/",
            "set_option Elab.async false",
            "",
        ]
        group_start = group * chunks_per_group
        group_stop = min(group_start + chunks_per_group, proof_chunk_count)
        for number in range(group_start, group_stop):
            group_lines.extend(
                [
                    "set_option maxHeartbeats 0 in",
                    "-- Exact reduction of one bounded certificate block.",
                    "set_option maxRecDepth 1000000 in",
                    f"theorem chunkValid{number} :",
                    "    ChunkValid",
                    f"      ⟨{number}, by norm_num [chunkCount]⟩ := by",
                    "  apply (checkChunk_eq_true_iff _).1",
                    "  rfl",
                    "",
                ]
            )
        group_lines.extend(
            [
                "set_option maxHeartbeats 0 in",
                "-- The explicit finite case split covers all 64 group offsets.",
                f"theorem groupValid{group} :",
                "    ChunkGroupValid",
                f"      ⟨{group}, by norm_num [groupCount]⟩ := by",
                "  intro offset hidx",
                "  fin_cases offset",
            ]
        )
        for offset in range(chunks_per_group):
            number = group * chunks_per_group + offset
            if number < proof_chunk_count:
                group_lines.append(
                    f"  · simpa [chunksPerGroup] using chunkValid{number}"
                )
            else:
                group_lines.append(
                    "  · norm_num [chunksPerGroup, chunkCount] at hidx"
                )
        group_lines.extend(
            ["", "end CleanLean.KL.FiniteRecordK12", ""]
        )
        group_path = PROOF_DIR / f"Group{group:02d}.lean"
        group_path.write_text("\n".join(group_lines))

    proof_lines = [
        "/- This file is generated by scripts/generate_finite_record_k12.py.",
        f"Source SHA-256: {source_hash}",
        "-/",
    ]
    for group in range(group_count):
        proof_lines.append(
            "import CleanLean.KL.FiniteRecordK12ChunkGroups."
            f"Group{group:02d}"
        )
    proof_lines.extend(
        [
            "",
            "namespace CleanLean.KL.FiniteRecordK12",
            "",
            "set_option maxHeartbeats 0 in",
            "-- The finite case split has one branch per independently checked group.",
            "/-- Assembly of the bounded groups. -/",
            "theorem allGroupsValid :",
            "    ∀ group : Fin groupCount, ChunkGroupValid group := by",
            "  intro group",
            "  fin_cases group",
        ]
    )
    for group in range(group_count):
        proof_lines.append(f"  · exact groupValid{group}")
    proof_lines.extend(
        [
            "",
            "/-- Assembly of all disjoint kernel-checked coordinate blocks. -/",
            "theorem allChunksValid :",
            "    ∀ chunk : Fin chunkCount, ChunkValid chunk :=",
            "  allChunksValid_of_groups allGroupsValid",
        ]
    )
    proof_lines.extend(["", "end CleanLean.KL.FiniteRecordK12", ""])
    PROOFS.write_text("\n".join(proof_lines))


if __name__ == "__main__":
    main()
