/- This file is generated by scripts/generate_finite_record_k12.py.
Source SHA-256: a6386bfc8d0410a3dd82a98d765690e53c620259e6b7c4a5359f150ce6d1459f
-/
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group00
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group01
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group02
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group03
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group04
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group05
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group06
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group07
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group08
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group09
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group10
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group11
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group12
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group13
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group14
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group15
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group16
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group17
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group18
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group19
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group20
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group21
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group22
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group23
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group24
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group25
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group26
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group27
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group28
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group29
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group30
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group31
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group32
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group33
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group34
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group35
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group36
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group37
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group38
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group39
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group40
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group41
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group42
import CleanLean.KL.FiniteRecordK12ChunkGroups.Group43

namespace CleanLean.KL.FiniteRecordK12

set_option maxHeartbeats 0 in
-- The finite case split has one branch per independently checked group.
/-- Assembly of the bounded groups. -/
theorem allGroupsValid :
    ∀ group : Fin groupCount, ChunkGroupValid group := by
  intro group
  fin_cases group
  · exact groupValid0
  · exact groupValid1
  · exact groupValid2
  · exact groupValid3
  · exact groupValid4
  · exact groupValid5
  · exact groupValid6
  · exact groupValid7
  · exact groupValid8
  · exact groupValid9
  · exact groupValid10
  · exact groupValid11
  · exact groupValid12
  · exact groupValid13
  · exact groupValid14
  · exact groupValid15
  · exact groupValid16
  · exact groupValid17
  · exact groupValid18
  · exact groupValid19
  · exact groupValid20
  · exact groupValid21
  · exact groupValid22
  · exact groupValid23
  · exact groupValid24
  · exact groupValid25
  · exact groupValid26
  · exact groupValid27
  · exact groupValid28
  · exact groupValid29
  · exact groupValid30
  · exact groupValid31
  · exact groupValid32
  · exact groupValid33
  · exact groupValid34
  · exact groupValid35
  · exact groupValid36
  · exact groupValid37
  · exact groupValid38
  · exact groupValid39
  · exact groupValid40
  · exact groupValid41
  · exact groupValid42
  · exact groupValid43

/-- Assembly of all disjoint kernel-checked coordinate blocks. -/
theorem allChunksValid :
    ∀ chunk : Fin chunkCount, ChunkValid chunk :=
  allChunksValid_of_groups allGroupsValid

end CleanLean.KL.FiniteRecordK12
