/-
Copyright (c) 2026 Simon DeDeo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Simon DeDeo, OpenAI Codex
-/
import CleanLean.KL.KLWeights

/-!
# Exact symbolic shifts for KL elimination paths

Every time shift generated by the KL splitter belongs to the rank-two lattice
`a + b * alpha`, with `a,b : ℤ`.  Retaining this pair is important for a
termination proof: the edge weights are not integers or rationals, and a
claimed negative control cycle must compare its exact symbolic weight rather
than a floating-point approximation.
-/

namespace CleanLean.KL

/-- An exact coordinate for the real shift `constant + alphaCoeff * alpha`. -/
structure SymbolicShift where
  constant : ℤ
  alphaCoeff : ℤ
  deriving DecidableEq, Repr

namespace SymbolicShift

/-- Evaluation in the real KL time coordinate. -/
noncomputable def value (s : SymbolicShift) : ℝ :=
  s.constant + s.alphaCoeff * alpha

/-- The root shift. -/
def zero : SymbolicShift := ⟨0, 0⟩

/-- A transport edge changes the shift by `-2`. -/
def transport (s : SymbolicShift) : SymbolicShift :=
  ⟨s.constant - 2, s.alphaCoeff⟩

/-- A retarded three-lift edge changes the shift by `alpha - 2`. -/
def retarded (s : SymbolicShift) : SymbolicShift :=
  ⟨s.constant - 2, s.alphaCoeff + 1⟩

/-- An advanced three-lift edge changes the shift by `alpha - 1`. -/
def advanced (s : SymbolicShift) : SymbolicShift :=
  ⟨s.constant - 1, s.alphaCoeff + 1⟩

@[simp] theorem value_zero : zero.value = 0 := by
  simp [zero, value]

@[simp] theorem value_transport (s : SymbolicShift) :
    s.transport.value = s.value - 2 := by
  simp [transport, value]
  ring

@[simp] theorem value_retarded (s : SymbolicShift) :
    s.retarded.value = s.value + (alpha - 2) := by
  simp [retarded, value]
  ring

@[simp] theorem value_advanced (s : SymbolicShift) :
    s.advanced.value = s.value + (alpha - 1) := by
  simp [advanced, value]
  ring

/-- The three kinds of principal-child edge in a concrete KL split. -/
inductive Step where
  | transport
  | retarded
  | advanced
  deriving DecidableEq, Repr

/-- Apply one symbolic path step. -/
def step : Step → SymbolicShift → SymbolicShift
  | .transport => transport
  | .retarded => retarded
  | .advanced => advanced

/-- Its exact real increment. -/
noncomputable def Step.increment : Step → ℝ
  | .transport => -2
  | .retarded => alpha - 2
  | .advanced => alpha - 1

@[simp] theorem value_step (kind : Step) (s : SymbolicShift) :
    (step kind s).value = s.value + kind.increment := by
  cases kind <;> simp [step, Step.increment, sub_eq_add_neg]

/-- Follow a finite word of control steps. -/
def follow : List Step → SymbolicShift → SymbolicShift
  | [], s => s
  | kind :: kinds, s => follow kinds (step kind s)

/-- The real weight of a finite control word. -/
noncomputable def wordWeight (kinds : List Step) : ℝ :=
  (kinds.map Step.increment).sum

/-- Translation invariance of the symbolic grammar: a word changes every
starting shift by the same exact weight. -/
theorem value_follow (kinds : List Step) (s : SymbolicShift) :
    (follow kinds s).value = s.value + wordWeight kinds := by
  induction kinds generalizing s with
  | nil => simp [follow, wordWeight]
  | cons kind kinds ih =>
      simp only [follow, ih, value_step, wordWeight, List.map_cons, List.sum_cons]
      ring

/-- For a nonnegative `alpha` coefficient, an exact upper bound on `alpha`
is enough to certify negativity of a symbolic cycle weight. -/
theorem value_neg_of_alpha_upper (s : SymbolicShift) (upper : ℝ)
    (hcoeff : 0 ≤ s.alphaCoeff) (halpha : alpha ≤ upper)
    (hbound : (s.constant : ℝ) + (s.alphaCoeff : ℝ) * upper < 0) :
    s.value < 0 := by
  have hc : (0 : ℝ) ≤ (s.alphaCoeff : ℝ) := by exact_mod_cast hcoeff
  have hmul : (s.alphaCoeff : ℝ) * alpha ≤
      (s.alphaCoeff : ℝ) * upper :=
    mul_le_mul_of_nonneg_left halpha hc
  rw [value]
  linarith

/-- For a nonpositive `alpha` coefficient, an exact lower bound on `alpha`
is enough to certify negativity. -/
theorem value_neg_of_alpha_lower (s : SymbolicShift) (lower : ℝ)
    (hcoeff : s.alphaCoeff ≤ 0) (halpha : lower ≤ alpha)
    (hbound : (s.constant : ℝ) + (s.alphaCoeff : ℝ) * lower < 0) :
    s.value < 0 := by
  have hc : (s.alphaCoeff : ℝ) ≤ 0 := by exact_mod_cast hcoeff
  have hmul : (s.alphaCoeff : ℝ) * alpha ≤
      (s.alphaCoeff : ℝ) * lower :=
    mul_le_mul_of_nonpos_left halpha hc
  rw [value]
  linarith

/-- Kernel-checkable upper-sandwich certificate for a symbolic cycle. -/
theorem value_neg_of_alpha_upper_check (s : SymbolicShift) (P Q : ℕ)
    (hcoeff : 0 ≤ s.alphaCoeff) (hQ : 0 < Q)
    (halpha : checkAlphaUpper P Q = true)
    (hbound : (s.constant : ℝ) +
      (s.alphaCoeff : ℝ) * ((P : ℝ) / (Q : ℝ)) < 0) :
    s.value < 0 := by
  apply value_neg_of_alpha_upper s ((P : ℝ) / (Q : ℝ)) hcoeff
  · exact (alpha_lt_div_of_check hQ halpha).le
  · exact hbound

/-- Kernel-checkable lower-sandwich certificate for a symbolic cycle. -/
theorem value_neg_of_alpha_lower_check (s : SymbolicShift) (P Q : ℕ)
    (hcoeff : s.alphaCoeff ≤ 0) (hQ : 0 < Q)
    (halpha : checkAlphaLower P Q = true)
    (hbound : (s.constant : ℝ) +
      (s.alphaCoeff : ℝ) * ((P : ℝ) / (Q : ℝ)) < 0) :
    s.value < 0 := by
  apply value_neg_of_alpha_lower s ((P : ℝ) / (Q : ℝ)) hcoeff
  · exact (div_lt_alpha_of_check hQ halpha).le
  · exact hbound

/-- A nonempty word consisting only of transport steps has strictly negative
weight.  Any nonnegative recurrent control cycle must therefore contain a
three-lift edge. -/
theorem wordWeight_replicate_transport_neg {n : ℕ} (hn : 0 < n) :
    wordWeight (List.replicate n Step.transport) < 0 := by
  have hnR : (0 : ℝ) < n := by exact_mod_cast hn
  have hneg : (n : ℝ) * (-2) < 0 :=
    mul_neg_of_pos_of_neg hnR (by norm_num)
  simpa [wordWeight, Step.increment] using hneg

end SymbolicShift

end CleanLean.KL
