/-
Copyright (c) 2026 Simon DeDeo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Simon DeDeo, OpenAI Codex
-/
import KontoroC.PacketTiming
import Mathlib.Data.Nat.ModEq
import Mathlib.Data.ZMod.Units
import Mathlib.GroupTheory.Index

/-!
# Generic congruence seams for a finite carry turnaround

These lemmas formalize two arithmetic interfaces used by the proposed
strike--scrub--turnaround cell: parity-compatible CRT, and writing an
arbitrary dyadic residue with an odd coefficient.  They assert existence of
one finite alignment, not an infinite rail.
-/

namespace KontoroC

theorem eight_dvd_twoPow_add_three (n : ℕ) :
    8 ∣ 2 ^ (n + 3) := by
  change 2 ^ 3 ∣ 2 ^ (n + 3)
  exact pow_dvd_pow 2 (by omega)

/-- Multiplication by an odd natural permutes every power-of-two residue
ring.  The witness is chosen canonically below the modulus. -/
theorem exists_oddCoefficient_solution_mod_twoPow
    (C v E : ℕ) (hC : Odd C) :
    ∃ w : ℕ, w < 2 ^ E ∧ C * w ≡ v [MOD 2 ^ E] := by
  let M := 2 ^ E
  have hM : 0 < M := by simp [M]
  letI : NeZero M := ⟨hM.ne'⟩
  have hcop : C.Coprime M := by
    dsimp [M]
    exact hC.coprime_two_right.pow_right E
  have hunit : IsUnit (C : ZMod M) :=
    (ZMod.isUnit_iff_coprime C M).2 hcop
  let wz : ZMod M := (C : ZMod M)⁻¹ * (v : ZMod M)
  let w := wz.val
  have hwcast : (w : ZMod M) = wz := ZMod.natCast_zmod_val wz
  refine ⟨w, ZMod.val_lt wz, ?_⟩
  rw [← ZMod.natCast_eq_natCast_iff]
  simp only [Nat.cast_mul, hwcast, wz]
  calc
    (C : ZMod M) * ((C : ZMod M)⁻¹ * (v : ZMod M)) =
        ((C : ZMod M) * (C : ZMod M)⁻¹) * (v : ZMod M) := by ring
    _ = v := by rw [ZMod.mul_inv_of_unit _ hunit, one_mul]

/-- Affine form of the same permutation statement. -/
theorem exists_oddCoefficient_affine_solution_mod_twoPow
    (C offset target E : ℕ) (hC : Odd C) :
    ∃ w : ℕ, w < 2 ^ E ∧
      C * w + offset ≡ target [MOD 2 ^ E] := by
  let M := 2 ^ E
  have hM : 0 < M := by simp [M]
  letI : NeZero M := ⟨hM.ne'⟩
  have hcop : C.Coprime M := by
    dsimp [M]
    exact hC.coprime_two_right.pow_right E
  have hunit : IsUnit (C : ZMod M) :=
    (ZMod.isUnit_iff_coprime C M).2 hcop
  let wz : ZMod M :=
    (C : ZMod M)⁻¹ * ((target : ZMod M) - (offset : ZMod M))
  let w := wz.val
  have hwcast : (w : ZMod M) = wz := ZMod.natCast_zmod_val wz
  refine ⟨w, ZMod.val_lt wz, ?_⟩
  rw [← ZMod.natCast_eq_natCast_iff]
  simp only [Nat.cast_add, Nat.cast_mul, hwcast, wz]
  calc
    (C : ZMod M) *
          ((C : ZMod M)⁻¹ * ((target : ZMod M) - offset)) + offset =
        ((C : ZMod M) * (C : ZMod M)⁻¹) *
          ((target : ZMod M) - offset) + offset := by ring
    _ = target := by rw [ZMod.mul_inv_of_unit _ hunit]; ring

/-- Modulo `2^(n+3)`, the units reducing to one modulo eight are exactly the
powers of nine.  The proof identifies the subgroup generated by nine with
the kernel of reduction to `(ZMod 8)ˣ`: both have cardinality `2^n`. -/
theorem exists_nine_pow_of_cast_eight_eq_one
    (n : ℕ)
    (u : (ZMod (2 ^ (n + 3)))ˣ)
    (hu : ZMod.unitsMap (eight_dvd_twoPow_add_three n) u = 1) :
    ∃ e : ℕ, (9 : ZMod (2 ^ (n + 3))) ^ e =
      (u : ZMod (2 ^ (n + 3))) := by
  let M := 2 ^ (n + 3)
  have hM : 0 < M := by simp [M]
  letI : NeZero M := ⟨hM.ne'⟩
  have hdiv : 8 ∣ M := by
    exact eight_dvd_twoPow_add_three n
  let f : (ZMod M)ˣ →* (ZMod 8)ˣ := ZMod.unitsMap hdiv
  have hcop : Nat.Coprime 9 M := by
    dsimp [M]
    exact (by norm_num : Nat.Coprime 9 2).pow_right (n + 3)
  let nine : (ZMod M)ˣ := ZMod.unitOfCoprime 9 hcop
  have hnine_mem : nine ∈ f.ker := by
    rw [MonoidHom.mem_ker]
    apply Units.ext
    simp only [f, nine, ZMod.unitsMap_val, ZMod.coe_unitOfCoprime,
      Units.val_one]
    rw [ZMod.cast_natCast hdiv]
    decide
  have hle : Subgroup.zpowers nine ≤ f.ker :=
    Subgroup.zpowers_le.mpr hnine_mem
  have hrange : f.range = ⊤ :=
    MonoidHom.range_eq_top.mpr (ZMod.unitsMap_surjective hdiv)
  have htargetCard : Nat.card (ZMod 8)ˣ = 4 := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient]
    decide
  have hsourceCard : Nat.card (ZMod M)ˣ = 2 ^ (n + 2) := by
    rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient]
    dsimp [M]
    convert Nat.totient_prime_pow_succ Nat.prime_two (n + 2) using 1
    · omega
  have hindex : f.ker.index = 4 := by
    rw [Subgroup.index_ker, hrange]
    simpa using htargetCard
  have hkerCard : Nat.card f.ker = 2 ^ n := by
    have hmul := f.ker.index_mul_card
    rw [hindex, hsourceCard] at hmul
    have hpow : 2 ^ (n + 2) = 4 * 2 ^ n := by
      rw [show n + 2 = 2 + n by omega, pow_add]
      norm_num
    rw [hpow] at hmul
    omega
  have hnineOrder : orderOf nine = 2 ^ n := by
    rw [← orderOf_units]
    change orderOf (9 : ZMod (2 ^ (n + 3))) = 2 ^ n
    exact orderOf_nine_twoPow n
  have hzpCard : Nat.card (Subgroup.zpowers nine) = 2 ^ n := by
    rw [Nat.card_eq_fintype_card, Fintype.card_zpowers, hnineOrder]
  have hset : (Subgroup.zpowers nine : Set (ZMod M)ˣ) = f.ker := by
    apply Set.Finite.eq_of_subset_of_card_le (Set.toFinite _) hle
    change Nat.card f.ker ≤ Nat.card (Subgroup.zpowers nine)
    rw [hkerCard, hzpCard]
  have hsubgroup : Subgroup.zpowers nine = f.ker :=
    SetLike.coe_injective hset
  have hu' : (u : (ZMod M)ˣ) ∈ f.ker := by
    rw [MonoidHom.mem_ker]
    simpa [f, M, hdiv] using hu
  have huz : (u : (ZMod M)ˣ) ∈ Subgroup.zpowers nine := by
    rw [hsubgroup]
    exact hu'
  have hpowers : (u : (ZMod M)ˣ) ∈ Submonoid.powers nine := by
    change u ∈ (Submonoid.powers nine : Set (ZMod M)ˣ)
    rw [(isOfFinOrder_of_finite nine).powers_eq_zpowers]
    exact huz
  obtain ⟨e, he⟩ := (Submonoid.mem_powers_iff u nine).mp hpowers
  refine ⟨e, ?_⟩
  have heval := congrArg (fun q : (ZMod M)ˣ => (q : ZMod M)) he
  simpa [M, nine, ZMod.coe_unitOfCoprime] using heval

/-- Required exponent form for the finite turnaround.  A unit that is one
modulo eight is first written as `9^e = 3^(2e)`.  Since 17 is odd, an affine
congruence then supplies an even `ell` with exponent `17*ell+40`. -/
theorem exists_even_turnaroundExponent_of_cast_eight_eq_one
    (n : ℕ)
    (u : (ZMod (2 ^ (n + 3)))ˣ)
    (hu : ZMod.unitsMap (eight_dvd_twoPow_add_three n) u = 1) :
    ∃ ell : ℕ, Even ell ∧
      (3 : ZMod (2 ^ (n + 3))) ^ (17 * ell + 40) =
        (u : ZMod (2 ^ (n + 3))) := by
  obtain ⟨e, he⟩ := exists_nine_pow_of_cast_eight_eq_one n u hu
  obtain ⟨w, _hwlt, hw⟩ :=
    exists_oddCoefficient_affine_solution_mod_twoPow 17 20 e n (by decide)
  refine ⟨2 * w, even_two_mul w, ?_⟩
  have hmod : 17 * (2 * w) + 40 ≡ 2 * e [MOD 2 ^ (n + 1)] := by
    have hdouble := hw.mul_left' 2
    convert hdouble using 1
    · rw [pow_succ]
      ring
    · ring
  have hp := (three_pow_eq_iff_modEq n (17 * (2 * w) + 40) (2 * e)).2 hmod
  calc
    (3 : ZMod (2 ^ (n + 3))) ^ (17 * (2 * w) + 40) =
        (3 : ZMod (2 ^ (n + 3))) ^ (2 * e) := hp
    _ = (9 : ZMod (2 ^ (n + 3))) ^ e := by
      rw [show (9 : ZMod (2 ^ (n + 3))) = 3 ^ 2 by norm_num,
        ← pow_mul]
    _ = u := he

/-- If two desired exponent classes are even, their halves can be combined
by ordinary CRT.  Doubling the result simultaneously restores the classes
modulo `2*3^k` and `2^(n+1)`. -/
theorem exists_parityCompatible_threePow_twoPow_crt
    (k n ellThree ellTwo : ℕ)
    (hThree : Even ellThree) (hTwo : Even ellTwo) :
    ∃ ell : ℕ, Even ell ∧
      ell ≡ ellThree [MOD 2 * 3 ^ k] ∧
      ell ≡ ellTwo [MOD 2 ^ (n + 1)] := by
  obtain ⟨a, ha⟩ := hThree
  obtain ⟨b, hb⟩ := hTwo
  have hcop : (3 ^ k).Coprime (2 ^ n) :=
    (by norm_num : Nat.Coprime 3 2).pow k n
  let c : ℕ := ↑(Nat.chineseRemainder hcop a b)
  refine ⟨2 * c, even_two_mul c, ?_, ?_⟩
  · have hc := (Nat.chineseRemainder hcop a b).property.1.mul_left' 2
    simpa [c, ha, two_mul] using hc
  · have hc := (Nat.chineseRemainder hcop a b).property.2.mul_left' 2
    simpa [c, hb, pow_succ, two_mul, mul_two, mul_comm] using hc

/-- An odd coefficient writes every prescribed half-residue.  This is the
form directly used after a turnaround expression has exposed one factor
`2`: the ambient congruence gains one binary digit. -/
theorem exists_oddCoefficient_dyadicWriter
    (C R v E : ℕ) (hC : Odd C) :
    ∃ w : ℕ, w < 2 ^ E ∧
      R + 2 * C * w ≡ R + 2 * v [MOD 2 ^ (E + 1)] := by
  obtain ⟨w, hwlt, hw⟩ :=
    exists_oddCoefficient_solution_mod_twoPow C v E hC
  refine ⟨w, hwlt, ?_⟩
  have hmul := hw.mul_left' 2
  have hadd := hmul.add_left R
  simpa [pow_succ, mul_assoc, mul_comm, mul_left_comm] using hadd

end KontoroC
